############################################
# SERVER CONFIGURATION
############################################
server.port=8080
server.address=0.0.0.0

############################################
# DATABASE
############################################
spring.datasource.url=jdbc:mysql://database-1.cne6y26k8ahr.ap-south-1.rds.amazonaws.com:3306/authifydb?useSSL=true&requireSSL=true&verifyServerCertificate=false&enabledTLSProtocols=TLSv1.2

spring.datasource.username=admin
spring.datasource.password=6202593257

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

############################################
# HIKARI
############################################
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=5

############################################
# JPA
############################################
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect

############################################
# JWT
############################################
auth.jwt.secret=Zk92bVZzNnJ3TGF0Q3hRTWVaM3VwZ0RTaUhYRmF3R1ZkM25BYWxPREp1bW13YzRj

auth.jwt.expiration=86400000

auth.jwt.refresh-expiration=604800000

############################################
# MAIL
############################################
spring.mail.host=email-smtp.ap-south-1.amazonaws.com

spring.mail.port=587

spring.mail.username=AKIAX3LRHIJIIUVZRN6C

spring.mail.password=BPo79hn3RMQw5f/IJMegSqTfgpCD9ALtZp6azk1ci9Sy

spring.mail.properties.mail.smtp.auth=true

spring.mail.properties.mail.smtp.starttls.enable=true

spring.mail.from=rohan2001.official@gmail.com

############################################
# LOGGING
############################################
logging.level.root=INFO
logging.level.in.bawvpl.Authify=DEBUG

############################################
# FILE
############################################
spring.servlet.multipart.max-file-size=1MB
spring.servlet.multipart.max-request-size=1MB

############################################
# TWILIO
############################################
app.sms.enabled=true
taws.s3.app-bucket=authify-app-assets76cd371d

twilio.token=136afb28081666683f6f56dd1e6845f8

twilio.number=+916202593257


admin.secret=SUPER_ADMIN_SECRET_Sandeep_2026

spring.jpa.properties.hibernate.default_batch_fetch_size=50

spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false
aws.region=ap-south-1
aws.s3.bucket=authify-kyc-prod
aws.access-key=${AWS_ACCESS_KEY_ID}
aws.secret-key=${AWS_SECRET_ACCESS_KEY}
aws.s3.profile-bucket=authify-profile-images
aws.s3.app-bucket=authify-app-assets